config/routes.rb
Rails.application.routes.draw do
  # get 'games/create'
  # get 'games/edit'
  # get 'games/update'
  # get 'games/show'
  # get 'pages/home'
  resources :games

  root to: 'pages#home'
  get 'pages/blog'
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

QUESTIONS = [
"A t'il les yeux clairs ?",
"Est-il un homme ?",
"Est-il vegan ?",
"Est-il originaire d'aquitaine ?"
]


  def create
    #create a new game!
    @game = Game.create
  	redirect_to edit_game_path(@game["id"], question_id: 0), method: :get
  end

  def edit
    @questions = QUESTIONS[params["question_id"].to_i]
  end

  def update
	  question_id = params["question_id"].to_i + 1
    @game = Game.find(params["id"])
    @game["answers"] << params["answers"]
    @game.save
    if question_id > 3
       redirect_to game_path(@game["id"]), method: :get
    else
       redirect_to edit_game_path(@game["id"], question_id: question_id), method: :get
    end
  end

  def show
    @game = Game.find(params["id"])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def blog
  	article1 = { 
	  "title" => "Objectif",
  	"content"=> "Notre objectif est d'appliquer au domaine des NTIC 
    (nouvelles technologies de l’information et de la communication) 
    des solutions innovantes élaborées par notre laboratoire de recherche 
    et développement en profitant des dernières avancées de la recherche.",
  	"rating" => 3
	}

	article2 = { 
	  "title" => "Projet futur",
  	"content"=> "Dans le domaine du divertissement, notre génie Akinator 
    est devenu une célebrité internationale du Web et du mobile et nous 
    travaillons continuellement sur son amélioration. Mais nous ne comptons 
    pas en rester là...",
  	"rating" => 3
  	}

	article3 = { 
	  "title" => "Au service de l'hunain",
  	"content"=> "Confrontés à une masse d'information de plus en plus collossale, 
    les utilisateurs d'aujourd'hui ont besoin d'outils intelligents qui les aident 
    à s'y retrouver, à obtenir facilement les réponses à leurs questions et à leurs 
    attentes. Mathilde et Loona participent à l'élaboration de ces solutions du futur 
    qui organiseront l'information en la mettant au service de l'humain.",
  	"rating" => 3
	}

	@articles = [ article1, article2, article3 ]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/games/edit.html.erb
<div class="background" style="background-image: url('https://image.freepik.com/free-vector/great-hand-drawn-wild-west-background-with-rocky-mountains_23-2147590302.jpg')">

	<h2><%= Question %></h2>
	<div class="btn_answers">

	<%= link_to "Oui", game_path(params[:id], answers: "yes", question_id: params["question_id"]), method: :path class: "btn btn-success btn-lg"%>

	<%= link_to "Non", game_path(params[:id], answers: "no", question_id: params["question_id"]), method: :path class: "btn btn-danger btn-lg"%>
	</div>


	<div class="btn_next">
	<%= link_to( "Continuer le jeu", game_path(1), method: :get, class: "btn btn-primary btn-lg" ) %>
	</div>

	<div class="akinator">
		<div class="row">
			<div class="col-12 col-sm-12 col-md-6 col-lg-3">
			</div>
			<div class="col-12 col-sm-12 col-md-6 col-lg-3">
				<img src="https://fr.akinator.com/bundles/elokencesite/images/akitudes_670x1096/defi.png?v95" alt="", class="avatar">
			</div>
		</div>
	</div>

</div>

app/views/games/show.html.erb
<div class="background" style="background-image: url('https://image.freepik.com/free-vector/great-hand-drawn-wild-west-background-with-rocky-mountains_23-2147590302.jpg')">

	<div class="akinator">
		<div class="row">
			<div class="col-12 col-sm-12 col-md-6 col-lg-3">
				<ul>
					<% @game = ["answers"].each do |answer| %>
						<li>Ma réponse est <%= answer %></li>
					<%= end %>
				</ul>
			</div>
			<div class="col-12 col-sm-12 col-md-6 col-lg-3">
				<img src="https://fr.akinator.com/bundles/elokencesite/images/akitudes_670x1096/defi.png?v95" alt="", class="avatar">
			</div>
		</div>
	</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>Akinator</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/blog.html.erb
<div class="background" style="background-image: url('https://image.freepik.com/free-vector/great-hand-drawn-wild-west-background-with-rocky-mountains_23-2147590302.jpg')">

	<h1>Qui sommes-nous ?</h1>


	<% @articles.each do |article| %>
		<div class= "article">
			<h2><%= article["title"] %></h2>
			
			<p><%= article["content"] %></p>
		</div>	

	<% end %>

</div>

app/views/pages/home.html.erb
<div class="background" style="background-image: url('https://image.freepik.com/free-vector/great-hand-drawn-wild-west-background-with-rocky-mountains_23-2147590302.jpg')">

	<h1>Akinator</h1>
	<div class="btn_game">
	<%= link_to( "Commencer le jeu", games_path, method: :post, class: "btn btn-primary btn-lg" ) %>
	</div>


	<div class="akinator">
		<div class="row">
			<div class="col-12 col-sm-12 col-md-6 col-lg-3">
				<img src="http://rosatubes.r.o.pic.centerblog.net/e55e8ede.png" alt="", class="bulle">
				<div class="pensees">
					<p>Je peux lire dans tes pensées</p>
				</div>	
			</div>
			<div class="col-12 col-sm-12 col-md-6 col-lg-3">
				<img src="https://fr.akinator.com/bundles/elokencesite/images/akitudes_670x1096/defi.png?v95" alt="", class="avatar">
			</div>
		</div>
	</div>
	    
	<div class="btn_blog">
	    <%= link_to( "Qui somnmes-nous ?", pages_blog_path, method: :get, class: "btn btn-secondary btn-lg btn-block" ) %>
	</div>

</div>